CREATE OR REPLACE FUNCTION DEDUCE_DOCTOR_FEE_ON_APPOINTMENT_REQ(P_ID IN NUMBER, D_ID IN NUMBER) RETURN VARCHAR2 IS
	C_FEE NUMBER;
	C_BALANCE NUMBER;
	C_BANKNO VARCHAR2(50);
	C_TDETAILS VARCHAR2(100);
	C_TTYPE VARCHAR2(50);
	C_INOUT VARCHAR2(10);
	C_DNAME VARCHAR2(50);
	MSG VARCHAR2(100);
BEGIN
	SELECT FEE INTO C_FEE FROM DOCTOR WHERE ID=D_ID;
	SELECT BALANCE INTO C_BALANCE FROM ACCOUNT WHERE PEOPLE_ID=P_ID;
	IF (C_BALANCE < C_FEE) THEN
		MSG := 'NOT ENOUGH BALANCE';
	ELSE
		C_BALANCE := C_BALANCE - C_FEE;
		UPDATE ACCOUNT SET BALANCE=C_BALANCE WHERE PEOPLE_ID=P_ID;
		
		SELECT NAME INTO C_DNAME FROM DOCTOR WHERE ID=D_ID;
		SELECT BANK_ACCOUNT_NO INTO C_BANKNO FROM ACCOUNT WHERE PEOPLE_ID=P_ID;
		C_TDETAILS := 'Requested an Appointment with : ' || C_DNAME;
		C_TTYPE := 'REQUESTING APPOINTMENT';
		C_INOUT := 'OUT';
		
		INSERT INTO TRANSACTIONS (BANK_ACCOUNT_NO, PEOPLE_ID, TRX_TYPE, DETAILS, TRX_DATE, AMOUNT, IN_OUT)
		VALUES (C_BANKNO, P_ID, C_TTYPE, C_TDETAILS, SYSDATE, C_FEE, C_INOUT);
		
		MSG := 'DONE';
	END IF;
	RETURN MSG;
EXCEPTION
	WHEN OTHERS THEN
		RETURN 'ERROR';
END;
/

--------------------------------------------------

