CREATE OR REPLACE PROCEDURE 
INSERT_INTO_MEDICINE(M_NAME IN VARCHAR2, M_TIME IN VARCHAR2) IS
	CURR_COUNT NUMBER;
BEGIN
	SELECT COUNT(*) INTO CURR_COUNT FROM MEDICINE M WHERE M.NAME LIKE M_NAME AND M.TIME LIKE M_TIME;
	IF CURR_COUNT = 0 THEN
		INSERT INTO MEDICINE (NAME, TIME) VALUES (M_NAME, M_TIME);
	END IF;
END;
/

---------------------------

CREATE OR REPLACE PROCEDURE INSERT_INTO_SONG(GSM_TITLE IN VARCHAR2) IS
	CURR_COUNT NUMBER;
BEGIN
	SELECT COUNT(*) INTO CURR_COUNT FROM SONG GSM WHERE GSM.TITLE LIKE GSM_TITLE;
	IF CURR_COUNT = 0 THEN
		INSERT INTO SONG (TITLE) VALUES (GSM_TITLE);
	END IF;
END;
/

----------------------------

CREATE OR REPLACE PROCEDURE INSERT_INTO_MOVIE(GSM_TITLE IN VARCHAR2) IS
	CURR_COUNT NUMBER;
BEGIN
	SELECT COUNT(*) INTO CURR_COUNT FROM MOVIE GSM WHERE GSM.TITLE LIKE GSM_TITLE;
	IF CURR_COUNT = 0 THEN
		INSERT INTO MOVIE (TITLE) VALUES (GSM_TITLE);
	END IF;
END;
/

-----------------------------

CREATE OR REPLACE PROCEDURE INSERT_INTO_GAME(GSM_TITLE IN VARCHAR2) IS
	CURR_COUNT NUMBER;
BEGIN
	SELECT COUNT(*) INTO CURR_COUNT FROM GAME GSM WHERE GSM.TITLE LIKE GSM_TITLE;
	IF CURR_COUNT = 0 THEN
		INSERT INTO GAME (TITLE) VALUES (GSM_TITLE);
	END IF;
END;
/

-----------------------------------

CREATE OR REPLACE PROCEDURE INSERT_INTO_DISEASE(D_NAME IN VARCHAR2) IS
	CURR_COUNT NUMBER;
BEGIN
	SELECT COUNT(*) INTO CURR_COUNT FROM DISEASE D WHERE D.NAME LIKE D_NAME;
	IF CURR_COUNT = 0 THEN
		INSERT INTO DISEASE (NAME) VALUES (D_NAME);
	END IF;
END;
/